Repository rust-lang/cc-rs, pull requests merged in 2025-01, with the labels that each got.

#1338 Document new supported architecture names in `windows_registry::find`
  src/windows/find_tools.rs
Labels: O-windows

#1347 Update `windows-bindgen` dependency
  dev-tools/gen-windows-sys-binding/Cargo.toml
  dev-tools/gen-windows-sys-binding/src/main.rs
  dev-tools/gen-windows-sys-binding/windows_sys.list
  src/windows/windows_sys.rs
Labels: dependencies, O-windows

#1328 Fix compiler family detection issue with clang-cl on macOS
  src/lib.rs
  src/tool.rs
  tests/test.rs
Labels: bug

#1364 Fix compilation on macOS using clang and fix compilation using zig-cc
  src/tool.rs
  tests/test.rs
Labels: bug, O-apple

#1361 Adjusted zig cc judgment and avoided zigbuild errors(#1360)
  src/tool.rs
Labels: bug

#1368 chore(ci) move ubuntu-20 job to ubuntu-22
  .github/workflows/main.yml
Labels: github_actions

#1371 Fix CC_FORCE_DISABLE=0 evaluating to true
  src/lib.rs
Labels: bug

#1339 Pass deployment target with `-m*-version-min=`
  dev-tools/gen-target-info/src/main.rs
  src/lib.rs
  src/target.rs
  src/target/apple.rs
  src/target/generated.rs
  src/target/llvm.rs
  src/target/parser.rs
  tests/test.rs
Labels: bug, O-apple

#1379 Constrain `-Clto` and `-Cembed-bitcode` flag inheritance to be `clang`-only
  src/flags.rs
Labels: bug

#1380 Fix more flag inheritance
  src/flags.rs
Labels: bug
